name: Update

on:
  workflow_dispatch:

jobs:
  detect:
    name: Detect kogama updates in markdown

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: check updates and download
        id: checks
        run: bash .github/workflows/scripts/check-version.sh

      - name: Get release url
        if: ${{ steps.checks.outputs.update == 'true' }}
        id: get_release
        uses: jonfriesen/get-release-by-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: versions

      - name: release if pending updates
        if: ${{ steps.checks.outputs.update == 'true' }}
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: "downloads/*.zip"

      - name: commit changes
        if: ${{ steps.checks.outputs.update == 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: 'versions.txt'
          message: Update versions.txt
          default_author: github_actions
